#cloud-config
package_update: true
package_upgrade: false

runcmd:
  - |
    cat > /etc/motd <<'EOF'
    Welcome!

    This system was provisioned using cloud-init.
    Some initialization tasks may still be running.

    To check status:
      cloud-init status
      tail -f /var/log/cloud-init.log
      tail -f /var/log/cloud-init-output.log
      cloud-init status --wait

    EOF

final_message: |
  Cloud-init finished.
  If this is your first login, please verify cloud-init status.
  To check status:
    cloud-init status
      tail -f /var/log/cloud-init.log
      tail -f /var/log/cloud-init-output.log
      cloud-init status --wait